# Generated by Django 5.2.3 on 2025-10-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
