# Generated by Django 5.2.3 on 2025-10-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_menuitem_image_menuitem_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStaff',
        ),
    ]
